[package]
name = "virus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
prost = "0.10"